### ISSUE TITLE
avoid forced use of a field ``name`` in every model

### ISSUE THREAD

**Issue by aorizondo** [alexanderaleskin/telegram_django_bot#15]
When listing a model instance fields the method ``gm_value_str`` from class ``TelegramViewset`` depends on the existance of one field called ``name`` in every defined model. Django has a similar behavior defining the ``__str__`` method in models for text rendering.

**Comment by aorizondo** [comment]
Also add documentation about the need to add field or property ``name`` to all models

**Comment by alexanderaleskin** [comment]
done for viewset and form
